name: Angular Build and Deploy

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14.x" # Example: specify the appropriate Node.js version here

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install Angular CLI and dependencies
        run: |
          npm install -g @angular/cli@<VERSION> # Specify Angular CLI version here
          npm install

      - name: Build Angular project
        run: ng build --prod 

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Copy built files to deployment directory
        run: |
          cp -r ./dist/angular-conduit-signals/* /var/www/html/Angular-PrivateSubnet
