name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Build Angular app
      run: npm run build
      
    - name: Copy files to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.KEY }} # Assuming you're using password-based authentication. Replace with secrets.KEY if using a key.
        source: "dist/angular-conduit-signals/*"
        target: "/var/www/html/Angular-PrivateSubnet"
